apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery
  namespace: chis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery
  template:
    metadata:
      labels:
        app: delivery
    spec:
      containers:
        - name: delivery
          image: 799491730030.dkr.ecr.us-east-1.amazonaws.com/chis-delivery:latest
          ports:
            - containerPort: 50051
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: chis-secret
                  key: DB_URL
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: chis-config
                  key: REDIS_URL
---
apiVersion: v1
kind: Service
metadata:
  name: delivery
  namespace: chis
spec:
  selector:
    app: delivery
  ports:
    - port: 50051
      targetPort: 50051
